routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Route::get('home', 'InstanceController@index');

Route::get('/emailVerification/{token}', function ($token) {
    $user = \App\User::where('email_token', $token)->first();

    if ($user instanceof \App\User) {
        $user->email_token = null;
        $user->verified = 1;
        $user->bill_date = date('Y-m-d', strtotime("+1 month"));
        $user->save();

        event(new \App\Events\UserWasCreated($user));

        flash()->success('Thank you for verifying your email address.');
        return redirect()->route('instance.index');
    }

    return response('Error', 404);
});

Route::get('/jobStatus/{jobId}', ['as' => 'jobStatus', 'middleware' => 'auth', function (\Cloudstack\CloudStackClient $acs, $jobId) {
    $result = $acs->queryAsyncJobResult(['jobid' => $jobId]);
    return response()->json($result);
}]);

Route::get('/progress/{jobId}', ['as' => 'progress', 'middleware' => 'auth', function ($jobId) {
    return view('progress', ['jobId' => $jobId]);
}]);

Auth::routes();

Route::resource('instance', 'InstanceController');
Route::resource('dns', 'DNSController', ['except' => ['show', 'update']]);
Route::post('dnsRecord', ['as' => 'dnsRecord.store', 'uses' => 'DNSController@storeRecord']);
Route::get('dnsRecord/{record}/edit', ['as' => 'dnsRecord.edit', 'uses' => 'DNSController@editRecord']);
Route::put('dnsRecord/{record}', ['as' => 'dnsRecord.update', 'uses' => 'DNSController@updateRecord']);
Route::patch('dnsRecord/{record}', 'DNSController@updateRecord');
Route::delete('dnsRecord/{record}', ['as' => 'dnsRecord.destroy', 'uses' => 'DNSController@destroyRecord']);

Route::get('instance/{instance}/start', ['as' => 'instance.start', 'uses' => 'InstanceController@start']);
Route::get('instance/{instance}/reboot', ['as' => 'instance.reboot', 'uses' => 'InstanceController@reboot']);
Route::get('instance/{instance}/stop', ['as' => 'instance.stop', 'uses' => 'InstanceController@stop']);
Route::get('instance/{instance}/restore', ['as' => 'instance.recover', 'uses' => 'InstanceController@recover']);
Route::get('instance/{instance}/snapshot', ['as' => 'instance.snapshot', 'uses' => 'InstanceController@snapshot']);
Route::get('instance/{instance}/resetpw', ['as' => 'instance.resetpw', 'uses' => 'InstanceController@resetPassword']);
Route::get('instance/{instance}/reinstallvm', ['as' => 'instance.reinstallvm', 'uses' => 'InstanceController@reinstallVirtualMachine']);

Route::get('snapshot/{snapshot}/createTemplate', ['as' => 'snapshot.newTemplate', 'uses' => 'InstanceController@newTemplateFromSnapshot']);
Route::post('snapshot/{snapshot}/createTemplate', ['as' => 'snapshot.createTemplate', 'uses' => 'InstanceController@createTemplateFromSnapshot']);
Route::get('snapshot/{snapshot}', ['as' => 'snapshot.deploy', 'uses' => 'InstanceController@deploySnapshot']);
Route::delete('snapshot/{snapshot}', ['as' => 'snapshot.destroy', 'uses' => 'InstanceController@deleteSnapshot']);

// Settings Section
Route::get('settings', ['as' => 'settings.profile', 'uses' => 'Settings\ProfileController@profile']);
Route::put('settings/profile', ['as' => 'settings.profile.update', 'uses' => 'Settings\ProfileController@update']);


Route::post('settings/vouchers/redeem', ['as' => 'settings.vouchers.redeem', 'uses' => 'Settings\VouchersController@redeem']);
Route::get('settings/security', ['as' => 'settings.security', 'uses' => 'Settings\SecurityController@index']);
Route::get('settings/billing', ['as' => 'settings.billing', 'uses' => 'Settings\BillingController@billing']);
Route::get('settings/billing/invoice/{id}', ['as' => 'invoice.show', 'uses' => 'Settings\BillingController@getInvoice']);
Route::get('settings/activity', ['as' => 'settings.activity', 'uses' => 'Settings\ActivityController@activity']);

Route::group(['as' => 'settings.'], function () {
    Route::resource('settings/vouchers', 'Settings\VouchersController', ['only' => ['index', 'update']]);
    Route::resource('settings/sshkeys', 'Settings\SSHKeyController', ['only' => ['store', 'destroy']]);
    Route::resource('settings/creditcard', 'Settings\CreditCardController', ['except' => ['index', 'show']]);
});


// Admin routes
Route::get('admin/', ['as' => 'admin.home', 'uses' => 'Admin\HomeController@index']);

Route::group(['as' => 'admin.'], function () {
    Route::resource('admin/template', 'Admin\TemplateController', ['except' => ['show']]);
    Route::resource('admin/package', 'Admin\PackageController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('admin/network', 'Admin\NetworkController');
    Route::resource('admin/user', 'Admin\UserController', ['except' => 'show']);
    Route::resource('admin/sg', 'Admin\SecurityGroupController', ['except' => ['edit', 'update']]);
});

Route::post('admin/sg/{id}/ingressrule', ['as' => 'admin.sg.ingressrule.add', 'uses' => 'Admin\SecurityGroupController@addIngressRule']);
Route::delete('admin/sg/ingressrule/{id}', ['as' => 'admin.sg.ingressrule.destroy', 'uses' => 'Admin\SecurityGroupController@deleteIngressRule']);

Route::get('admin/zone', ['as' => 'admin.zone.index', 'uses' => 'Admin\ZoneController@index']);
Route::get('admin/zone/{zone}/edit', ['as' => 'admin.zone.edit', 'uses' => 'Admin\ZoneController@edit']);
Route::put('admin/zone/{zone}', ['as' => 'admin.zone.update', 'uses' => 'Admin\ZoneController@update']);
Route::patch('admin/zone/{zone}', 'Admin\ZoneController@update');
Route::get('admin/settings', ['as' => 'admin.settings.index', 'uses' => 'Admin\SettingsController@index']);
Route::get('admin/settings/edit', ['as' => 'admin.settings.edit', 'uses' => 'Admin\SettingsController@edit']);
Route::post('admin/settings', ['as' => 'admin.settings.save', 'uses' => 'Admin\SettingsController@save']);
Route::get('admin/settings/updateCloud', ['as' => 'admin.settings.updateCloud', 'uses' => 'Admin\SettingsController@updateCloud']);
Route::get('admin/setup', ['as' => 'admin.setup.index', 'uses' => 'Admin\SetupController@index']);
Route::post('admin/setup', ['as' => 'admin.setup.save', 'uses' => 'Admin\SetupController@save']);
Route::get('admin/profile', ['as' => 'admin.profile.edit', 'uses' => 'Admin\ProfileController@edit']);
Route::patch('admin/profile', ['as' => 'admin.profile.update', 'uses' => 'Admin\ProfileController@update']);

resources/views/adminapp.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cloud Billing Administration</title>

    <link rel="icon" href="../../favicon.ico">

    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{{ asset('/css/dashboard.css') }}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">{{ Config::get('app.name') }} Administration</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="/home">Portal</a></li>
                <li><a href="{{ route('admin.profile.edit') }}">Profile</a></li>
                <li>
                    <a href="{{ url('/logout') }}"
                        onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li{!! Request::is('admin/package*') ? ' class="active"' : '' !!}><a href="{{ route('admin.package.index') }}">Packages <span class="sr-only">(current)</span></a></li>
                <li{!! Request::is('admin/sg*') ? ' class="active"' : '' !!}><a href="{{ route('admin.sg.index') }}">Security Groups</a></li>
                <li{!! Request::is('admin/template*') ? ' class="active"' : '' !!}><a href="{{ route('admin.template.index') }}">Templates</a></li>
                <li{!! Request::is('admin/user*') ? ' class="active"' : '' !!}><a href="{{ route('admin.user.index') }}">Users</a></li>
                <li{!! Request::is('admin/zone*') ? ' class="active"' : '' !!}><a href="{{ route('admin.zone.index') }}">Zones</a></li>
                <li{!! Request::is('admin/settings*') ? ' class="active"' : '' !!}><a href="{{ route('admin.settings.index') }}">Settings</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            @include('flash::message')

            @yield('content')
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script>
    @yield('js')
</script>
</body>
</html>

resources/views/appold.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Cloud Billing</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
@yield('modals')

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Cloud Billing</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
                    <li><a href="{{ route('instance.index') }}">Instances</a></li>
                    <li><a href="{{ route('dns.index') }}">DNS</a></li>
                    <li><a href="{{ route('settings.profile') }}">Settings</a></li>
                    @if (!Auth::guest())
                        @if ('Admin' == Auth::user()->access)
                            <li><a href="{{ route('admin.home') }}">Admin</a></li>
                        @endif
                    @endif
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Sign Up!</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

    @include('flash::message')

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script>
    <script>
        @yield('js')
    </script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('contentNOINCLUDE')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!<br/>
                    <a href="{{ route('instance.create') }}">New Virtual Machine</a><br/>
                    <a href="{{ route('instance.index') }}">Instances</a><br/>
                    <a href="{{ route('settings.profile') }}">Settings</a><br/>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/please-validate.blade.php
@extends('layouts.app-guest')

@section('content')
    <p>Thank you for registering.  Please validate your email address before proceeding.</p>
@endsection

resources/views/progress.blade.php
@extends('layouts.app')

@section('content')
    <h3>Please wait while we process your request.</h3>

    <div class="progress" style="width: 80%">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">

        </div>
    </div>
@endsection

@section('js')
    function checkStatus(jobId) {
        $.ajax({
            type: "GET",
            url: '/jobStatus/' + jobId, //resource
            success: function(result) {
                console.log(result);
                if (result.jobstatus == 1)
                {
                    if (result.jobinstancetype == 'VirtualMachine')
                    {
                        // Redirect to a good location
                        window.location = '/instance/' + result.jobinstanceid;

                    }
                    else
                    {
                        window.location = '/instance/';
                    }

                } else {
                    // Call this again.
                    setTimeout(function() { checkStatus('{{ $jobId }}'); }, 3000);
                }
            }
        });
    }

    $(document).ready(function() {
        setTimeout(function() { checkStatus('{{ $jobId }}'); }, 3000);
    });
@endsection