routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Route::get('home', 'InstanceController@index');

Route::get('/emailVerification/{token}', function ($token) {
    $user = \App\User::where('email_token', $token)->first();

    if ($user instanceof \App\User) {
        $user->email_token = null;
        $user->verified = 1;
        $user->bill_date = date('Y-m-d', strtotime("+1 month"));
        $user->save();

        event(new \App\Events\UserWasCreated($user));

        flash()->success('Thank you for verifying your email address.');
        return redirect()->route('instance.index');
    }

    return response('Error', 404);
});

Route::get('/jobStatus/{jobId}', ['as' => 'jobStatus', 'middleware' => 'auth', function (\Cloudstack\CloudStackClient $acs, $jobId) {
    $result = $acs->queryAsyncJobResult(['jobid' => $jobId]);
    return response()->json($result);
}]);

Route::get('/progress/{jobId}', ['as' => 'progress', 'middleware' => 'auth', function ($jobId) {
    return view('progress', ['jobId' => $jobId]);
}]);

Auth::routes();

Route::resource('instance', 'InstanceController');
Route::resource('dns', 'DNSController', ['except' => ['show', 'update']]);
Route::post('dnsRecord', ['as' => 'dnsRecord.store', 'uses' => 'DNSController@storeRecord']);
Route::get('dnsRecord/{record}/edit', ['as' => 'dnsRecord.edit', 'uses' => 'DNSController@editRecord']);
Route::put('dnsRecord/{record}', ['as' => 'dnsRecord.update', 'uses' => 'DNSController@updateRecord']);
Route::patch('dnsRecord/{record}', 'DNSController@updateRecord');
Route::delete('dnsRecord/{record}', ['as' => 'dnsRecord.destroy', 'uses' => 'DNSController@destroyRecord']);

Route::get('instance/{instance}/start', ['as' => 'instance.start', 'uses' => 'InstanceController@start']);
Route::get('instance/{instance}/reboot', ['as' => 'instance.reboot', 'uses' => 'InstanceController@reboot']);
Route::get('instance/{instance}/stop', ['as' => 'instance.stop', 'uses' => 'InstanceController@stop']);
Route::get('instance/{instance}/restore', ['as' => 'instance.recover', 'uses' => 'InstanceController@recover']);
Route::get('instance/{instance}/snapshot', ['as' => 'instance.snapshot', 'uses' => 'InstanceController@snapshot']);
Route::get('instance/{instance}/resetpw', ['as' => 'instance.resetpw', 'uses' => 'InstanceController@resetPassword']);
Route::get('instance/{instance}/reinstallvm', ['as' => 'instance.reinstallvm', 'uses' => 'InstanceController@reinstallVirtualMachine']);

Route::get('snapshot/{snapshot}/createTemplate', ['as' => 'snapshot.newTemplate', 'uses' => 'InstanceController@newTemplateFromSnapshot']);
Route::post('snapshot/{snapshot}/createTemplate', ['as' => 'snapshot.createTemplate', 'uses' => 'InstanceController@createTemplateFromSnapshot']);
Route::get('snapshot/{snapshot}', ['as' => 'snapshot.deploy', 'uses' => 'InstanceController@deploySnapshot']);
Route::delete('snapshot/{snapshot}', ['as' => 'snapshot.destroy', 'uses' => 'InstanceController@deleteSnapshot']);

// Settings Section
Route::get('settings', ['as' => 'settings.profile', 'uses' => 'Settings\ProfileController@profile']);
Route::put('settings/profile', ['as' => 'settings.profile.update', 'uses' => 'Settings\ProfileController@update']);


Route::post('settings/vouchers/redeem', ['as' => 'settings.vouchers.redeem', 'uses' => 'Settings\VouchersController@redeem']);
Route::get('settings/security', ['as' => 'settings.security', 'uses' => 'Settings\SecurityController@index']);
Route::get('settings/billing', ['as' => 'settings.billing', 'uses' => 'Settings\BillingController@billing']);
Route::get('settings/billing/invoice/{id}', ['as' => 'invoice.show', 'uses' => 'Settings\BillingController@getInvoice']);
Route::get('settings/activity', ['as' => 'settings.activity', 'uses' => 'Settings\ActivityController@activity']);

Route::group(['as' => 'settings.'], function () {
    Route::resource('settings/vouchers', 'Settings\VouchersController', ['only' => ['index', 'update']]);
    Route::resource('settings/sshkeys', 'Settings\SSHKeyController', ['only' => ['store', 'destroy']]);
    Route::resource('settings/creditcard', 'Settings\CreditCardController', ['except' => ['index', 'show']]);
});


// Admin routes
Route::get('admin/', ['as' => 'admin.home', 'uses' => 'Admin\HomeController@index']);

Route::group(['as' => 'admin.'], function () {
    Route::resource('admin/template', 'Admin\TemplateController', ['except' => ['show']]);
    Route::resource('admin/package', 'Admin\PackageController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('admin/network', 'Admin\NetworkController');
    Route::resource('admin/user', 'Admin\UserController', ['except' => 'show']);
    Route::resource('admin/sg', 'Admin\SecurityGroupController', ['except' => ['edit', 'update']]);
});

Route::post('admin/sg/{id}/ingressrule', ['as' => 'admin.sg.ingressrule.add', 'uses' => 'Admin\SecurityGroupController@addIngressRule']);
Route::delete('admin/sg/ingressrule/{id}', ['as' => 'admin.sg.ingressrule.destroy', 'uses' => 'Admin\SecurityGroupController@deleteIngressRule']);

Route::get('admin/zone', ['as' => 'admin.zone.index', 'uses' => 'Admin\ZoneController@index']);
Route::get('admin/zone/{zone}/edit', ['as' => 'admin.zone.edit', 'uses' => 'Admin\ZoneController@edit']);
Route::put('admin/zone/{zone}', ['as' => 'admin.zone.update', 'uses' => 'Admin\ZoneController@update']);
Route::patch('admin/zone/{zone}', 'Admin\ZoneController@update');
Route::get('admin/settings', ['as' => 'admin.settings.index', 'uses' => 'Admin\SettingsController@index']);
Route::get('admin/settings/edit', ['as' => 'admin.settings.edit', 'uses' => 'Admin\SettingsController@edit']);
Route::post('admin/settings', ['as' => 'admin.settings.save', 'uses' => 'Admin\SettingsController@save']);
Route::get('admin/settings/updateCloud', ['as' => 'admin.settings.updateCloud', 'uses' => 'Admin\SettingsController@updateCloud']);
Route::get('admin/setup', ['as' => 'admin.setup.index', 'uses' => 'Admin\SetupController@index']);
Route::post('admin/setup', ['as' => 'admin.setup.save', 'uses' => 'Admin\SetupController@save']);
Route::get('admin/profile', ['as' => 'admin.profile.edit', 'uses' => 'Admin\ProfileController@edit']);
Route::patch('admin/profile', ['as' => 'admin.profile.update', 'uses' => 'Admin\ProfileController@update']);

resources/views/admin/template/create.blade.php
@extends('adminapp')

@section('content')
<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">New Template Group</div>
        <div class="panel-body">
            {!! Form::open(['method' => 'POST', 'route' => 'admin.template.store', 'class' => 'form-horizontal', 'files' => true]) !!}

            <!-- Name Form Input -->
            <div class="form-group">
                {!! Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('type', 'Type', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-2">
                    {!! Form::select('type', ['IaaS' => 'IaaS', 'SaaS' => 'SaaS'], null, ['class' => 'form-control']) !!}
                </div>
            </div>

            <!-- Display_img Form Input -->
            <div class="form-group">
                {!! Form::label('display_img', 'Display Image', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::file('display_img') !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('templates', 'Templates', ['class' => 'col-sm-3 control-label']) !!} <br/>
                <div class="col-sm-6">
                    @foreach ($templates as $template)
                        @if($template->templatetype !== "BUILTIN")
                            {!! Form::hidden('templates[' . $template->id . ']', '0') !!}
                        @endif
                        @if(property_exists($template, "size"))
                            {!! Form::hidden('templateSize[' . $template->id . ']', ($template->size / 1024 / 1024 / 1024)) !!}
                        @endif
                        @if($template->templatetype !== "BUILTIN")
                            {!! Form::checkbox('templates[' . $template->id . ']') !!}
                        @endif
                        {{ $template->displaytext }} 
                        @if(property_exists($template, "size"))
                            ({{ ($template->size / 1024 / 1024 / 1024) }} Gb)
                        @endif<br/>
                    @endforeach
                </div>
            </div>

            <!-- Form Submit -->
            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    {!! Form::reset('Reset', ['class' => 'btn btn-default']) !!}
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/admin/template/edit.blade.php
@extends('adminapp')

@section('content')
<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">Edit Template Group</div>
        <div class="panel-body">
            {!! Form::model($group, ['method' => 'PATCH', 'route' => ['admin.template.update', $group->id], 'class' => 'form-horizontal']) !!}

            <!-- Name Form Input -->
            <div class="form-group">
                {!! Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('type', 'Type', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-2">
                    {!! Form::select('type', ['IaaS' => 'IaaS', 'SaaS' => 'SaaS'], null, ['class' => 'form-control']) !!}
                </div>
            </div>

            <!-- Display_img Form Input -->
            <div class="form-group">
                {!! Form::label('display_img', 'Display Image', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::file('display_img') !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('templates', 'Templates', ['class' => 'col-sm-3 control-label']) !!} <br/>
                <div class="col-sm-6">
                    @foreach ($templates as $template)
                        @if(property_exists($template, "size"))
                            {!! Form::hidden('templateSize[' . $template->id . ']', ($template->size / 1024 / 1024 / 1024)) !!}
                        @endif
                        @if($template->templatetype !== "BUILTIN")
                            {!! Form::checkbox('templates[' . $template->id . ']', 1, (in_array($template->id, $checkedIDs)) ? true : false) !!} 
                        @endif
                        {{ $template->displaytext }}
                        @if(property_exists($template, "size"))
                            ({{ ($template->size / 1024 / 1024 / 1024) }} Gb)
                        @endif<br/>
                    @endforeach
                </div>
            </div>

            <!-- Form Submit -->
            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    {!! Form::reset('Reset', ['class' => 'btn btn-default']) !!}
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>



@endsection

resources/views/admin/template/index.blade.php
@extends('adminapp')

@section('content')
<table class="table">
    <thead>
    <tr>
        <th>Template Group Name</th>
        <th>Type</th>
        <th>Template Count</th>
        <th><a href="{{ route('admin.template.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></th>
    </tr>
    </thead>
    <tbody>
    @foreach ($groups as $group)
        <tr>
            <td>{{ $group->name }}</td>
            <td>{{ $group->type }}</td>
            <td>{{ $group->templates->count() }}</td>
            <td>
                <a href="{{ route('admin.template.edit', $group->id) }}" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a href="javascript:deleteTemplate({{ $group->id }})" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection

@section('js')
function deleteTemplate(id) {
    if (confirm('Delete this template group?')) {
        $.ajax({
            type: "DELETE",
            headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
            url: '/admin/template/' + id, //resource
            success: function(affectedRows) {
                //if something was deleted, we redirect the user to the users page, and automatically the user that he deleted will disappear
                if (affectedRows > 0) window.location = '/admin/template/';
            }
        });
    }
}
@endsection

resources/views/admin/template/show.blade.php
@extends('adminapp')

@section('content')
    Template Group - {{ $group->name }} - {{ $group->type }}<br/><br/>

    @foreach ($templates as $template)
        <li>{{ $template->size }} - {{ $template->price }}</li>
    @endforeach
@endsection